language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - python create_table.py

script:
  - nosetests

after_success:
  - codecov
